package ro.galactus.client;

import net.minecraft.client.model.*;
import net.minecraft.client.render.*;
import net.minecraft.client.render.entity.model.EntityModel;
import net.minecraft.client.util.math.MatrixStack;
import ro.galactus.CosmicEntity;

/** Art data generated by generate_character_art.py; articulated animation below. */
public class CosmicModel extends EntityModel<CosmicEntity> {
    private final ModelPart root, head, body, leftArm, rightArm, leftLeg, rightLeg;
    private final boolean surfer;
    public CosmicModel(ModelPart root, boolean surfer) {
        this.root=root;this.surfer=surfer;head=root.getChild("head");body=root.getChild("body");
        leftArm=root.getChild("left_arm");rightArm=root.getChild("right_arm");
        leftLeg=root.getChild("left_leg");rightLeg=root.getChild("right_leg");
    }
    public static TexturedModelData data() {
        var model=new ModelData();var r=model.getRoot();
        var body=r.addChild("body",ModelPartBuilder.create().uv(0,0).cuboid(-5f,0f,-3f,10f,10f,6f).uv(34,0).cuboid(-5.5f,0f,-3.5f,11f,4f,7f).uv(72,0).cuboid(-4.5f,4f,-3.4f,9f,5f,6.8f).uv(106,0).cuboid(-1.5f,1f,-4f,3f,5f,1f).uv(116,0).cuboid(-1f,2f,-4.3f,2f,2f,0.5f).uv(124,0).cuboid(-4f,5f,-3.7f,2f,3f,0.6f).uv(132,0).cuboid(2f,5f,-3.7f,2f,3f,0.6f).uv(140,0).cuboid(-5.5f,9f,-3.5f,11f,2f,7f).uv(178,0).cuboid(-2f,9f,-3.8f,4f,2f,1f).uv(190,0).cuboid(-5f,11f,-3.4f,3f,4f,1f).uv(200,0).cuboid(2f,11f,-3.4f,3f,4f,1f).uv(210,0).cuboid(-1.5f,11f,-3.5f,3f,3f,1f).uv(220,0).cuboid(-1f,6f,-3.75f,2f,0.35f,0.35f),ModelTransform.of(0f,0f,0f,0f,0f,0f));
        var head=r.addChild("head",ModelPartBuilder.create().uv(228,0).cuboid(-3.5f,-6f,-3f,7f,6f,6f).uv(256,0).cuboid(-3.5f,-8f,-3.4f,7f,2f,6.8f).uv(286,0).cuboid(-4f,-7f,-3.5f,1f,7f,7f).uv(304,0).cuboid(3f,-7f,-3.5f,1f,7f,7f).uv(322,0).cuboid(-3f,-1f,-3.5f,6f,1f,1f).uv(338,0).cuboid(-3f,-6f,-3.5f,6f,1.5f,1f).uv(354,0).cuboid(-1f,-8.5f,-4f,2f,4f,1f).uv(362,0).cuboid(-2.6f,-4.8f,-3.35f,2f,0.65f,0.4f).uv(370,0).cuboid(0.6f,-4.8f,-3.35f,2f,0.65f,0.4f).uv(378,0).cuboid(-2.5f,-4.6f,-3.6f,1.8f,0.45f,0.4f).uv(386,0).cuboid(0.7f,-4.6f,-3.6f,1.8f,0.45f,0.4f).uv(394,0).cuboid(-0.6f,-4f,-3.8f,1.2f,2f,1f).uv(402,0).cuboid(-1.6f,-1.8f,-3.2f,3.2f,0.4f,0.4f).uv(414,0).cuboid(-2f,-1.3f,-3.25f,4f,0.8f,0.5f).uv(426,0).cuboid(-3f,-3.8f,-3.4f,1.2f,2f,0.6f).uv(434,0).cuboid(1.8f,-3.8f,-3.4f,1.2f,2f,0.6f),ModelTransform.of(0f,-1f,0f,0f,0f,0f));
        var leftVane=head.addChild("left_vane",ModelPartBuilder.create().uv(442,0).cuboid(-1f,-7f,-2f,2f,9f,4f).uv(456,0).cuboid(-1.3f,-8f,-2.5f,2.6f,2f,5f).uv(474,0).cuboid(-0.45f,-6f,-2.3f,0.9f,7f,0.5f).uv(480,0).cuboid(-1.6f,-9.5f,-2.2f,3.2f,2f,4.4f),ModelTransform.of(3.8f,-4f,0f,0f,0f,0.27f));
        var leftArm=r.addChild("left_arm",ModelPartBuilder.create().uv(0,18).cuboid(-2.5f,-1.5f,-3.5f,5f,4f,7f).uv(26,18).cuboid(-2.7f,-1.8f,-3.8f,5.4f,1f,7.6f).uv(56,18).cuboid(-1.7f,2f,-2.3f,3.4f,5f,4.6f),ModelTransform.of(6f,1f,0f,0f,0f,0f));
        var leftForearm=leftArm.addChild("forearm",ModelPartBuilder.create().uv(76,18).cuboid(-2f,0f,-2.5f,4f,5f,5f).uv(96,18).cuboid(-2.3f,0f,-2.8f,4.6f,1.2f,5.6f).uv(120,18).cuboid(-2.3f,4f,-2.8f,4.6f,1.2f,5.6f).uv(144,18).cuboid(-1.8f,5f,-2.3f,3.6f,3f,4.6f).uv(164,18).cuboid(-1.4f,6f,-2.7f,2.8f,1.5f,0.7f),ModelTransform.of(0f,7f,0f,0f,0f,0f));
        var leftLeg=r.addChild("left_leg",ModelPartBuilder.create().uv(174,18).cuboid(-2.2f,0f,-2.3f,4.4f,6f,4.6f).uv(196,18).cuboid(-2.4f,1f,-2.6f,4.8f,4f,1f),ModelTransform.of(2.8f,11f,0f,0f,0f,0f));
        var leftShin=leftLeg.addChild("shin",ModelPartBuilder.create().uv(210,18).cuboid(-2.4f,0f,-2.7f,4.8f,2f,5.4f).uv(234,18).cuboid(-2.2f,2f,-2.4f,4.4f,4f,4.8f).uv(256,18).cuboid(-0.6f,2f,-2.6f,1.2f,4f,0.5f).uv(264,18).cuboid(-2.5f,5f,-3.5f,5f,2f,7f).uv(290,18).cuboid(-2.6f,6f,-3.6f,5.2f,1f,7.2f),ModelTransform.of(0f,6f,0f,0f,0f,0f));
        var rightVane=head.addChild("right_vane",ModelPartBuilder.create().uv(320,18).cuboid(-1f,-7f,-2f,2f,9f,4f).uv(334,18).cuboid(-1.3f,-8f,-2.5f,2.6f,2f,5f).uv(352,18).cuboid(-0.45f,-6f,-2.3f,0.9f,7f,0.5f).uv(358,18).cuboid(-1.6f,-9.5f,-2.2f,3.2f,2f,4.4f),ModelTransform.of(-3.8f,-4f,0f,0f,0f,-0.27f));
        var rightArm=r.addChild("right_arm",ModelPartBuilder.create().uv(378,18).cuboid(-2.5f,-1.5f,-3.5f,5f,4f,7f).uv(404,18).cuboid(-2.7f,-1.8f,-3.8f,5.4f,1f,7.6f).uv(434,18).cuboid(-1.7f,2f,-2.3f,3.4f,5f,4.6f),ModelTransform.of(-6f,1f,0f,0f,0f,0f));
        var rightForearm=rightArm.addChild("forearm",ModelPartBuilder.create().uv(454,18).cuboid(-2f,0f,-2.5f,4f,5f,5f).uv(474,18).cuboid(-2.3f,0f,-2.8f,4.6f,1.2f,5.6f).uv(0,33).cuboid(-2.3f,4f,-2.8f,4.6f,1.2f,5.6f).uv(24,33).cuboid(-1.8f,5f,-2.3f,3.6f,3f,4.6f).uv(44,33).cuboid(-1.4f,6f,-2.7f,2.8f,1.5f,0.7f),ModelTransform.of(0f,7f,0f,0f,0f,0f));
        var rightLeg=r.addChild("right_leg",ModelPartBuilder.create().uv(54,33).cuboid(-2.2f,0f,-2.3f,4.4f,6f,4.6f).uv(76,33).cuboid(-2.4f,1f,-2.6f,4.8f,4f,1f),ModelTransform.of(-2.8f,11f,0f,0f,0f,0f));
        var rightShin=rightLeg.addChild("shin",ModelPartBuilder.create().uv(90,33).cuboid(-2.4f,0f,-2.7f,4.8f,2f,5.4f).uv(114,33).cuboid(-2.2f,2f,-2.4f,4.4f,4f,4.8f).uv(136,33).cuboid(-0.6f,2f,-2.6f,1.2f,4f,0.5f).uv(144,33).cuboid(-2.5f,5f,-3.5f,5f,2f,7f).uv(170,33).cuboid(-2.6f,6f,-3.6f,5.2f,1f,7.2f),ModelTransform.of(0f,6f,0f,0f,0f,0f));
        return TexturedModelData.of(model,512,512);
    }
    public static TexturedModelData heraldData() {
        var model=new ModelData();var r=model.getRoot();
        var body=r.addChild("body",ModelPartBuilder.create().uv(0,0).cuboid(-3.5f,0f,-2f,7f,5f,4f).uv(24,0).cuboid(-2.5f,5f,-1.5f,5f,6f,3f).uv(42,0).cuboid(-3f,10f,-2f,6f,2f,4f).uv(64,0).cuboid(-3.4f,1f,-2.5f,3f,3f,1f).uv(74,0).cuboid(0.4f,1f,-2.5f,3f,3f,1f).uv(84,0).cuboid(-2f,5f,-1.9f,4f,2f,1f).uv(96,0).cuboid(-1.5f,7f,-1.8f,3f,2f,1f),ModelTransform.of(0f,0f,0f,0f,0f,0f));
        var head=r.addChild("head",ModelPartBuilder.create().uv(106,0).cuboid(-1f,-1f,-1f,2f,2f,2f).uv(116,0).cuboid(-2.5f,-6f,-2f,5f,5f,4f).uv(136,0).cuboid(-2f,-2f,-2.3f,4f,1f,1f).uv(148,0).cuboid(-0.5f,-4f,-2.6f,1f,2f,1f).uv(154,0).cuboid(-1.8f,-4.2f,-2.2f,1.3f,0.45f,0.3f).uv(162,0).cuboid(0.5f,-4.2f,-2.2f,1.3f,0.45f,0.3f).uv(170,0).cuboid(-0.9f,-2.1f,-2.5f,1.8f,0.25f,0.2f),ModelTransform.of(0f,0f,0f,0f,0f,0f));
        var leftArm=r.addChild("left_arm",ModelPartBuilder.create().uv(178,0).cuboid(-1.5f,-1f,-1.7f,3f,3f,3.4f).uv(194,0).cuboid(-1.2f,2f,-1.4f,2.4f,4f,2.8f),ModelTransform.of(4f,1f,0f,0f,0f,0f));
        var leftForearm=leftArm.addChild("forearm",ModelPartBuilder.create().uv(208,0).cuboid(-1.2f,0f,-1.2f,2.4f,4f,2.4f).uv(222,0).cuboid(-1f,4f,-1.1f,2f,2f,2.2f).uv(234,0).cuboid(0.7f,4f,-1.1f,1f,1f,1f),ModelTransform.of(0f,6f,0f,0f,0f,0f));
        var leftLeg=r.addChild("left_leg",ModelPartBuilder.create().uv(240,0).cuboid(-1.4f,0f,-1.5f,2.8f,6f,3f),ModelTransform.of(1.8f,11f,0f,0f,0f,0f));
        var leftShin=leftLeg.addChild("shin",ModelPartBuilder.create().uv(254,0).cuboid(-1.1f,0f,-1.2f,2.2f,6f,2.4f).uv(268,0).cuboid(-1.2f,5.5f,-2.5f,2.4f,1.2f,4f),ModelTransform.of(0f,6f,0f,0f,0f,0f));
        var rightArm=r.addChild("right_arm",ModelPartBuilder.create().uv(284,0).cuboid(-1.5f,-1f,-1.7f,3f,3f,3.4f).uv(300,0).cuboid(-1.2f,2f,-1.4f,2.4f,4f,2.8f),ModelTransform.of(-4f,1f,0f,0f,0f,0f));
        var rightForearm=rightArm.addChild("forearm",ModelPartBuilder.create().uv(314,0).cuboid(-1.2f,0f,-1.2f,2.4f,4f,2.4f).uv(328,0).cuboid(-1f,4f,-1.1f,2f,2f,2.2f).uv(340,0).cuboid(-0.7f,4f,-1.1f,1f,1f,1f),ModelTransform.of(0f,6f,0f,0f,0f,0f));
        var rightLeg=r.addChild("right_leg",ModelPartBuilder.create().uv(346,0).cuboid(-1.4f,0f,-1.5f,2.8f,6f,3f),ModelTransform.of(-1.8f,11f,0f,0f,0f,0f));
        var rightShin=rightLeg.addChild("shin",ModelPartBuilder.create().uv(360,0).cuboid(-1.1f,0f,-1.2f,2.2f,6f,2.4f).uv(374,0).cuboid(-1.2f,5.5f,-2.5f,2.4f,1.2f,4f),ModelTransform.of(0f,6f,0f,0f,0f,0f));
        var board=r.addChild("board",ModelPartBuilder.create().uv(390,0).cuboid(-4f,-0.25f,-10f,8f,0.8f,20f).uv(448,0).cuboid(-3.5f,-0.45f,-13f,7f,0.8f,3f).uv(470,0).cuboid(-2.5f,-0.7f,-15f,5f,0.8f,2f).uv(486,0).cuboid(-1.5f,-0.9f,-16f,3f,0.8f,1f).uv(0,23).cuboid(-3.5f,-0.25f,10f,7f,0.8f,3f).uv(22,23).cuboid(-2.5f,-0.25f,13f,5f,0.8f,2f).uv(38,23).cuboid(-1.5f,-0.25f,15f,3f,0.8f,1f).uv(48,23).cuboid(-4f,0.1f,-9f,0.3f,0.4f,18f).uv(88,23).cuboid(3.7f,0.1f,-9f,0.3f,0.4f,18f).uv(128,23).cuboid(-0.2f,-0.35f,-12f,0.4f,0.1f,24f),ModelTransform.of(0f,24f,0f,0f,0f,0f));
        return TexturedModelData.of(model,512,512);
    }
    @Override public void setAngles(CosmicEntity e,float limb,float amount,float age,float yaw,float pitch) {
        root.traverse().forEach(ModelPart::resetTransform);
        float breath=(float)Math.sin(age*.035);
        head.yaw=Math.max(-.45f,Math.min(.45f,yaw*.017453292f));
        head.pitch=Math.max(-.2f,Math.min(.2f,pitch*.017453292f));
        if(surfer) {
            root.roll=breath*.035f;
            body.yaw=.24f;head.yaw-=.15f;
            leftArm.roll=-1.0f-breath*.035f;rightArm.roll=.65f+breath*.035f;
            leftArm.pitch=-.35f;rightArm.pitch=.15f;
            leftArm.getChild("forearm").pitch=-.32f;rightArm.getChild("forearm").pitch=-.24f;
            leftLeg.pitch=-.28f;rightLeg.pitch=.17f;
            leftLeg.roll=-.26f;rightLeg.roll=.26f;
            leftLeg.getChild("shin").pitch=.25f;rightLeg.getChild("shin").pitch=.12f;
            root.getChild("board").pitch=breath*.025f;
            root.getChild("board").yaw=1.5707963f;
        } else {
            body.pitch=breath*.008f;
            leftArm.roll=-.08f;rightArm.roll=.08f;
            leftArm.pitch=breath*.025f;rightArm.pitch=-breath*.025f;
            leftArm.getChild("forearm").pitch=-.12f;rightArm.getChild("forearm").pitch=-.12f;
        }
    }
    @Override public void render(MatrixStack matrices,VertexConsumer vertices,int light,int overlay,int color) {
        root.render(matrices,vertices,light,overlay,color);
    }
}
